### ISSUE TITLE
Package name and repo name difference

### ISSUE THREAD

**Issue by yakuter** [fatihkahveci/simple-matchmaking#2]
When the package name and repo name are different as in below, it increases complexity.

repo name: `github.com/fatihkahveci/simple-matchmaking`
package name: `simple_mm`

I think you should change both with a single easy name like "matchmaker" or anything you like.

Then you should change the NewMatchmaking function name as New because it is already being called with package name.

`matchmaker.NewMatchmaking` <- Bad
`matchmaker.New` <- Good and idiomatic ;)

**Comment by fatihkahveci** [comment]
I absolutely miss that package name typo wow good catch 😄
